/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.CarrierDAO;
import dao.DBConnection;
import javax.swing.JFrame;

/**
 *
 * @author ramona.wuthrich
 */
public class MainFrame extends javax.swing.JFrame {
    private DBConnection myConn;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        initComponents();
        myConn = new DBConnection();
        try{
            myConn.Open();
        }
        catch(Exception e){
            System.out.println("Problem opening connection");
        }
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
         
        // Instantiate frames for most tables in the DB
        CarrierFrame c = new CarrierFrame(myConn);
        //CustomerFrame u = new CustomerFrame(myConn);
        //EmployeeFrame e = new EmployeeFrame(myConn);
        //EquipmentFrame q = new EquipmentFrame(myConn);
        //PartFrame p = new PartFrame(myConn);
        //VendorFrame v = new VendorFrame(myConn);
        //OrderFrame o = new OrderFrame(myConn);
        //RepairOrderFrame r = new RepairOrderFrame(myConn);
        
        //add the contents of each frame to their appropriate panels
        PanelCarrier.add(c.getContentPane());
        //PanelCustomer.add(u.getContentPane());
        //PanelEmployee.add(d.getContentPane());
        //PanelEquipment.add(q.getContentPane());
        //PanelPart.add(p.getContentPane());
        //PanelVendor.add(v.getContentPane());
        //PanelOrder.add(o.getContentPane());
        //PanelRerpairOrder.add(r.getContentPane());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneEcho = new javax.swing.JTabbedPane();
        PanelHome = new javax.swing.JPanel();
        PanelRepairOrder = new javax.swing.JPanel();
        PanelPartOrder = new javax.swing.JPanel();
        PanelCustomer = new javax.swing.JPanel();
        PanelEquipment = new javax.swing.JPanel();
        PanelCarrier = new javax.swing.JPanel();
        PanelEmployee = new javax.swing.JPanel();
        PanelPart = new javax.swing.JPanel();
        PanelVendor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPaneEcho.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        javax.swing.GroupLayout PanelHomeLayout = new javax.swing.GroupLayout(PanelHome);
        PanelHome.setLayout(PanelHomeLayout);
        PanelHomeLayout.setHorizontalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelHomeLayout.setVerticalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Home", PanelHome);

        javax.swing.GroupLayout PanelRepairOrderLayout = new javax.swing.GroupLayout(PanelRepairOrder);
        PanelRepairOrder.setLayout(PanelRepairOrderLayout);
        PanelRepairOrderLayout.setHorizontalGroup(
            PanelRepairOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelRepairOrderLayout.setVerticalGroup(
            PanelRepairOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Repair Orders", PanelRepairOrder);

        javax.swing.GroupLayout PanelPartOrderLayout = new javax.swing.GroupLayout(PanelPartOrder);
        PanelPartOrder.setLayout(PanelPartOrderLayout);
        PanelPartOrderLayout.setHorizontalGroup(
            PanelPartOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelPartOrderLayout.setVerticalGroup(
            PanelPartOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Part Orders", PanelPartOrder);

        javax.swing.GroupLayout PanelCustomerLayout = new javax.swing.GroupLayout(PanelCustomer);
        PanelCustomer.setLayout(PanelCustomerLayout);
        PanelCustomerLayout.setHorizontalGroup(
            PanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelCustomerLayout.setVerticalGroup(
            PanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Customers", PanelCustomer);

        javax.swing.GroupLayout PanelEquipmentLayout = new javax.swing.GroupLayout(PanelEquipment);
        PanelEquipment.setLayout(PanelEquipmentLayout);
        PanelEquipmentLayout.setHorizontalGroup(
            PanelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelEquipmentLayout.setVerticalGroup(
            PanelEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Equipment", PanelEquipment);

        javax.swing.GroupLayout PanelCarrierLayout = new javax.swing.GroupLayout(PanelCarrier);
        PanelCarrier.setLayout(PanelCarrierLayout);
        PanelCarrierLayout.setHorizontalGroup(
            PanelCarrierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelCarrierLayout.setVerticalGroup(
            PanelCarrierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Carriers", PanelCarrier);

        javax.swing.GroupLayout PanelEmployeeLayout = new javax.swing.GroupLayout(PanelEmployee);
        PanelEmployee.setLayout(PanelEmployeeLayout);
        PanelEmployeeLayout.setHorizontalGroup(
            PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelEmployeeLayout.setVerticalGroup(
            PanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Employees", PanelEmployee);

        javax.swing.GroupLayout PanelPartLayout = new javax.swing.GroupLayout(PanelPart);
        PanelPart.setLayout(PanelPartLayout);
        PanelPartLayout.setHorizontalGroup(
            PanelPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelPartLayout.setVerticalGroup(
            PanelPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Parts", PanelPart);

        javax.swing.GroupLayout PanelVendorLayout = new javax.swing.GroupLayout(PanelVendor);
        PanelVendor.setLayout(PanelVendorLayout);
        PanelVendorLayout.setHorizontalGroup(
            PanelVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelVendorLayout.setVerticalGroup(
            PanelVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        TabbedPaneEcho.addTab("Vendors", PanelVendor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneEcho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TabbedPaneEcho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private javax.swing.JLabel HomeLabel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCarrier;
    private javax.swing.JPanel PanelCustomer;
    private javax.swing.JPanel PanelEmployee;
    private javax.swing.JPanel PanelEquipment;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelPart;
    private javax.swing.JPanel PanelPartOrder;
    private javax.swing.JPanel PanelRepairOrder;
    private javax.swing.JPanel PanelVendor;
    private javax.swing.JTabbedPane TabbedPaneEcho;
    // End of variables declaration//GEN-END:variables
}
